config/routes.rb
First::Application.routes.draw do
  get "sessions/new"

  resources :devices

  resources :departments

  resources :ustroystvas

  resources :sotrudnikis

  resources :microposts

  resources :menu

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'public#menu'
  match '/',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to:sotrudnikis
  belongs_to:departments

  attr_accessible :Dev_type, :amortization, :date_intr, :date_kil, :date_of_introduce, :department, :dev_cost, :dev_name, :district, :invent_number, :object_operation, :operation_dat, :worker
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end
  #def setAmortization
    #@devices.each do |device|
   # @devices = Device.all
   # tmp=amortization.to_f
   # tmp=dev_cost.to_f/4.0
   # amortization=tmp.to_s
   # "#{tmp}"
   # end
  #end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Тип_устройства %><br />
    <%= f.text_field :Dev_type %>
  </div>
  <div class="field">
    <%= f.label :Название %><br />
    <%= f.text_field :dev_name %>
  </div>
  <div class="field">
    <%= f.label :Сотрудник %><br />
    <%= collection_select(:sotrudniki, :name, Sotrudniki.all, :id, :worker_name) %>
  </div>
  <div class="field">
    <%= f.label :Инвертарный_номер %><br />
    <%= f.text_field :invent_number %>
  </div>
  <div class="field">
    <%= f.label :Отдел %><br />
    <%= collection_select(:department, :name, Department.all, :id, :department_name) %>
  </div>
  <div class="field">
    <%= f.label :Цена %><br />
    <%= f.text_field :dev_cost %>
  </div>
  <div class="field">
    <%= f.label :Дата_ввода %><br />
    <%= f.text_field :date_intr %>
  </div>
  <div class="field">
    <%= f.label :Дата_выпуска %><br />
    <%= f.text_field :date_of_introduce %>
  </div>
  <div class="field">
    <%= f.label :Списание %><br />
    <%= f.check_box :object_operation %>
  </div>
  <div class="field">
    <%= f.label :Дата_проведения %><br />
    <%= f.text_field :operation_dat %>
  </div>
  <div class="field">
    <%= f.label :Дата_списания %><br />
    <%= f.text_field :date_kil %>
  </div>
  <div class="field">
    <%= f.label :Амортизация %><br />
    <%= f.text_field :amortization %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<meta charset="UTF-8">
<h1>Устройства</h1>
<%= title "Список устройств" %>
<div id="sidebar">Перейти в таблицу: <a href="/departments">Отделы</a>
  <a href="/sotrudnikis">Сотрудники</a></div>
<table>
  <tr>
    <th>Тип</th>
    <th>Название</th>
    <th>Отдел</th>
    <th>Сотрудник</th>
    <th>Инвент_номер</th>
    <th>District</th>
    <th>Цена</th>
    <th>Дата ввода</th>
    <th>Дата выпуска</th>
    <th>Операция</th>
    <th>Дата операции</th>
    <th>Дата списания</th>
    <th>Амортизация</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>

  <tr>
    <td><%= device.Dev_type %></td>
    <td><%= device.dev_name %></td>
    <td><%= device.department %></td>
    <td><%= device.worker %></td>
    <td><%= device.invent_number %></td>
    <td><%= device.district %></td>
    <td><%= device.dev_cost %></td>
    <td><%= device.date_intr %></td>
    <td><%= device.date_of_introduce %></td>
    <td><%= device.object_operation %></td>
    <td><%= device.operation_dat %></td>
    <td><%= device.date_kil %></td>
    <td><%= device.amortization %></td>
    <td><%= link_to 'Посмотреть', device %></td>
    <td><%= link_to 'Редактировать', edit_device_path(device) %></td>
    <td><%= link_to 'Удалить', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= button_to'Пересчитать амортизацию',method: :setAmortization, data: {confirm: 'Are you sure?'} %>
<%= link_to 'Добавить', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dev type:</b>
  <%= @device.Dev_type %>
</p>

<p>
  <b>Dev name:</b>
  <%= @device.dev_name %>
</p>

<p>
  <b>Department:</b>
  <%= @device.department %>
</p>

<p>
  <b>Worker:</b>
  <%= @device.worker %>
</p>

<p>
  <b>Invent number:</b>
  <%= @device.invent_number %>
</p>

<p>
  <b>District:</b>
  <%= @device.district %>
</p>

<p>
  <b>Dev cost:</b>
  <%= @device.dev_cost %>
</p>

<p>
  <b>Date intr:</b>
  <%= @device.date_intr %>
</p>

<p>
  <b>Date of introduce:</b>
  <%= @device.date_of_introduce %>
</p>

<p>
  <b>Object operation:</b>
  <%= @device.object_operation %>
</p>

<p>
  <b>Operation dat:</b>
  <%= @device.operation_dat %>
</p>

<p>
  <b>Date kil:</b>
  <%= @device.date_kil %>
</p>

<p>
  <b>Amortization:</b>
  <%= @device.amortization %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>