config/routes.rb
First::Application.routes.draw do
  get "sessions/new"

  resources :devices

  resources :departments

  resources :ustroystvas

  resources :sotrudnikis

  resources :microposts

  resources :menu

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'public#menu'
  match '/',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/department.rb
class Department < ActiveRecord::Base
has_many:devices
has_many:sotrudnikis
belongs_to:sotrudnikis
  attr_accessible :manager, :name, :short_name
def department_name
  "#{name}"
end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Название %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Аббревиатура %><br />
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :Начальник %><br />
    <%= collection_select(:sotrudniki, :name, Sotrudniki.all, :id, :worker_name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<h1>Список отделов</h1>
<%= title "Список отделов" %>
<div id="sidebar">Перейти в таблицу:    <a href="/devices">Устройства</a>
<a href="/sotrudnikis">   Сотрудники</a></div>
<table>
  <tr>
    <th>Название</th>
    <th>Абревиатура</th>
    <th>Начальник</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @departments.each do |department| %>
  <tr>
    <td><%= department.name %></td>
    <td><%= department.short_name %></td>
    <td><%= department.manager %></td>
    <td><%= link_to 'Посмотреть', department %></td>
    <td><%= link_to 'Редактировать', edit_department_path(department) %></td>
    <td><%= link_to 'Удалить', department, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новый отдел', new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @department.name %>
</p>

<p>
  <b>Short name:</b>
  <%= @department.short_name %>
</p>

<p>
  <b>Manager:</b>
  <%= @department.manager %>
</p>


<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>