config/routes.rb
First::Application.routes.draw do
  get "sessions/new"

  resources :devices

  resources :departments

  resources :ustroystvas

  resources :sotrudnikis

  resources :microposts

  resources :menu

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'public#menu'
  match '/',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/sotrudniki.rb
class Sotrudniki < ActiveRecord::Base

  before_save :encrypt_password

  def has_password?(submitted_password)
    password == submitted_password
  end

  private

  def encrypt_password
    self.salt = make_salt if new_record?

  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(tab_number, cookie_salt)
    user = find_by_id(tab_number)
    (user && user.salt == cookie_salt) ? user : nil
  end
  has_many:devices
  belongs_to:departments
  attr_accessible :access, :adress, :district, :email, :job, :name, :password,:salt, :short_name, :tab_number, :telephone, :username
  def worker_name
    "#{name}"
  end
end

app/controllers/sotrudnikis_controller.rb
class SotrudnikisController < ApplicationController
  # GET /sotrudnikis
  # GET /sotrudnikis.json
  def index
    @sotrudnikis = Sotrudniki.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sotrudnikis }
    end
  end

  # GET /sotrudnikis/1
  # GET /sotrudnikis/1.json
  def show
    @sotrudniki = Sotrudniki.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sotrudniki }
    end
  end

  # GET /sotrudnikis/new
  # GET /sotrudnikis/new.json
  def new
    @sotrudniki = Sotrudniki.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sotrudniki }
    end
  end

  # GET /sotrudnikis/1/edit
  def edit
    @sotrudniki = Sotrudniki.find(params[:id])
  end

  # POST /sotrudnikis
  # POST /sotrudnikis.json
  def create
    @sotrudniki = Sotrudniki.new(params[:sotrudniki])

    respond_to do |format|
      if @sotrudniki.save
        format.html { redirect_to @sotrudniki, notice: 'Sotrudniki was successfully created.' }
        format.json { render json: @sotrudniki, status: :created, location: @sotrudniki }
      else
        format.html { render action: "new" }
        format.json { render json: @sotrudniki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sotrudnikis/1
  # PUT /sotrudnikis/1.json
  def update
    @sotrudniki = Sotrudniki.find(params[:id])

    respond_to do |format|
      if @sotrudniki.update_attributes(params[:sotrudniki])
        format.html { redirect_to @sotrudniki, notice: 'Sotrudniki was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sotrudniki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sotrudnikis/1
  # DELETE /sotrudnikis/1.json
  def destroy
    @sotrudniki = Sotrudniki.find(params[:id])
    @sotrudniki.destroy

    respond_to do |format|
      format.html { redirect_to sotrudnikis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sotrudnikis_helper.rb
module SotrudnikisHelper
	def title(page_title)
		content_for :title, page_title.to_s
	end
end

app/views/sotrudnikis/_form.html.erb
<%= title "Сотрудники"%>

<%= form_for(@sotrudniki) do |f| %>
  <% if @sotrudniki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sotrudniki.errors.count, "error") %> prohibited this sotrudniki from being saved:</h2>

      <ul>
      <% @sotrudniki.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Таб_номер %><br />
    <%= f.number_field :tab_number %>
  </div>
  <div class="field">
    <%= f.label :ФИО %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Короткое_имя %><br />
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :Отдел %><br />
    <%= collection_select(:department, :name, Department.all, :id, :department_name)%>
  </div>
  <div class="field">
    <%= f.label :Должность %><br />
    <%= f.text_field :job %>
  </div>
  <div class="field">
    <%= f.label :Адрес %><br />
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :Телефон %><br />
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :Доступ %><br />
    <%= f.check_box :access %>
  </div>
    <div class="field">
      <%= f.label :Pass %><br />
      <%= f.text_field :password %>
    </div>
  <div class="actions">
    <%= f.submit "Сохранить"%>
  </div>
<% end %>

app/views/sotrudnikis/edit.html.erb
<h1>Редактировать</h1>

<%= render 'form' %>

<%= link_to 'Посмотреть', @sotrudniki %> |
<%= link_to 'Назад', sotrudnikis_path %>

app/views/sotrudnikis/index.html.erb
<meta charset="UTF-8">
<%= title "Список сотрудников" %>
<h1>Сотрудники</h1>
<div id="sidebar">Перейти в таблицу: <a href="/departments">Отделы </a><a href="/devices">Устройства</a></div>
<table>
  <tr>
    <th>Таб_номер</th>
    <th>ФИО</th>
    <th>Короткое имя</th>
    <th>Username</th>
    <th>Email</th>
    <th>Отдел</th>
    <th>Должность</th>
    <th>Адрес</th>
    <th>Телефон</th>
    <th>Доступ</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @sotrudnikis.each do |sotrudniki| %>
      <tr>
        <td><%= sotrudniki.tab_number %></td>
        <td><%= sotrudniki.name %></td>
        <td><%= sotrudniki.short_name %></td>
        <td><%= sotrudniki.username %></td>
        <td><%= sotrudniki.email %></td>
        <td><%= sotrudniki.district %></td>
        <td><%= sotrudniki.job %></td>
        <td><%= sotrudniki.adress %></td>
        <td><%= sotrudniki.telephone %></td>
        <td><%= sotrudniki.access %></td>

        <td><%= link_to 'Посмотреть', sotrudniki %></td>
        <td><%= link_to 'Редактировать', edit_sotrudniki_path(sotrudniki) %></td>
        <td><%= link_to 'Удалить', sotrudniki, method: :delete, data: {confirm: 'Вы уверены?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'Добавить', new_sotrudniki_path %>

app/views/sotrudnikis/new.html.erb
<h1>Новый сотрудник</h1>

<%= render 'form' %>

<%= link_to 'Назад', sotrudnikis_path %>

app/views/sotrudnikis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Таб_номер:</b>
  <%= @sotrudniki.tab_number %>
</p>

<p>
  <b>ФИО:</b>
  <%= @sotrudniki.name %>
</p>

<p>
  <b>Короткое имя:</b>
  <%= @sotrudniki.short_name %>
</p>

<p>
  <b>Username:</b>
  <%= @sotrudniki.username %>
</p>

<p>
  <b>Email:</b>
  <%= @sotrudniki.email %>
</p>

<p>
  <b>Отдел:</b>
  <%= @sotrudniki.district %>
</p>

<p>
  <b>Должность:</b>
  <%= @sotrudniki.job %>
</p>

<p>
  <b>Адрес:</b>
  <%= @sotrudniki.adress %>
</p>

<p>
  <b>Телефон:</b>
  <%= @sotrudniki.telephone %>
</p>

<p>
  <b>Доступ:</b>
  <%= @sotrudniki.access %>
</p>


<%= link_to 'Редактировать', edit_sotrudniki_path(@sotrudniki) %> |
<%= link_to 'Назад', sotrudnikis_path %>